import img1 from "../images/Cars/Mercedes-Benz-G-Class.png";
import img2 from "../images/Cars/Mercedes-Benz-GLA.png";
import img3 from "../images/Cars/Mercedes-Benz-GLC-Coupe.png";
import img4 from "../images/Cars/Mercedes-Benz-GLS.png";
import img5 from "../images/Cars/Mercedes-Benz-S-Class.png";
import img6 from "../images/Cars/Porsche-Cayenne.png";
import img7 from "../images/Cars/Porsche-Macan-Turbo-EV.png";
import img8 from "../images/Cars/Porsche-Taycan.png";
import img9 from "../images/Cars/Porsche-Cayenne.png";
import img10 from "../images/Cars/Aston Martin DB11.jpg";
import img11 from "../images/Cars/Audi Q3.jpg";
import img12 from "../images/Cars/Audi Q7.jpg";
import img13 from "../images/Cars/jeep grand cherokee.jpg";
import img14 from "../images/Cars/jeep wrangler.jpg";
import img15 from "../images/Cars/land rover defender.jpg";
import img16 from "../images/Cars/Land Rover range rover.jpg";

export const carData = [
    {
        id: ("609e451f60c175001eab94ff"),
        name: "Mercedes-Benz G-Class",
        brand: "Mercedes-Benz",
        type: "SUV",
        price: 150,
        image: img1,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 4,
    },
    {
        id: ("609e451f60c175001eab92ff"),
        name: "Mercedes-Benz GLA",
        brand: "Mercedes-Benz",
        type: "SUV",
        price: 120,
        image: img2,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 10,
        ratings: 3,
    },
    {
        id: ("609e451f60c175001eab91ff"),

        name: "Mercedes-Benz GLC Coupe",
        brand: "Mercedes-Benz",
        type: "SUV",
        price: 140,
        image: img3,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 4,
    },
    {
        id: ("609e451f60c175001eab90ff"),

        name: "Mercedes-Benz GLS",
        brand: "Mercedes-Benz",
        type: "SUV",
        price: 180,
        image: img4,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 5,
    },
    {
        id: ("609e451f60c175001eab85ff"),

        name: "Mercedes-Benz S-Class",
        brand: "Mercedes-Benz",
        type: "Luxury Sedan",
        price: 250,
        image: img5,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 5,
    },
    {
        id: ("609e451f60c175001eab15ff"),

        name: "Porsche Cayenne",
        brand: "Porsche",
        type: "SUV",
        price: 200,
        image: img6,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 4,
    },
    {
        id: ("609d451f60c175001eab95ff"),

        name: "Porsche Macan Turbo EV",
        brand: "Porsche",
        type: "SUV",
        price: 220,
        image: img7,
        fuelType: "Electric",
        transmission: "Automatic",
        discount: 0,
        ratings: 4,
    },
    {
        id: ("612e451f60c175001eab95ff"),

        name: "Porsche Taycan",
        brand: "Porsche",
        type: "Electric Sedan",
        price: 280,
        image: img8,
        fuelType: "Electric",
        transmission: "Automatic",
        discount: 0,
        ratings: 5,
    },
    {
        id: ("149e451f60c175001eab95ff"),

        name: "Porsche 911",
        brand: "Porsche",
        type: "Sports Car",
        price: 300,
        image: img9,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 5,
    },
    {
        id: ("6044451f60c175001eab95ff"),

        name: "Aston Martin DB11",
        brand: "Aston Martin",
        type: "Luxury Sports Car",
        price: 350,
        image: img10,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 4,
    },
    {
        id: ("609d551f60c175001eab95ff"),

        name: "Audi Q3",
        brand: "Audi",
        type: "SUV",
        price: 100,
        image: img11,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 5,
        ratings: 3,
    },
    {
        id: ("609e781f60c175001eab95ff"),
        name: "Audi Q7",
        brand: "Audi",
        type: "SUV",
        price: 160,
        image: img12,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 4,
    },
    {
        id: ("609e451f60c144001eab95ff"),

        name: "Jeep Grand Cherokee",
        brand: "Jeep",
        type: "SUV",
        price: 130,
        image: img13,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 10,
        ratings: 4,
    },
    {
        id: ("609e451f111175001eab95ff"),

        name: "Jeep Wrangler",
        brand: "Jeep",
        type: "SUV",
        price: 140,
        image: img14,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 4,
    },
    {
        id: ("609e451f70c175001eab95ff"),

        name: "Land Rover Defender",
        brand: "Land Rover",
        type: "SUV",
        price: 200,
        image: img15,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 5,
    },
    {
        id: ("609e651f60c175001eab95ff"),

        name: "Land Rover Range Rover",
        brand: "Land Rover",
        type: "SUV",
        price: 250,
        image: img16,
        fuelType: "Gasoline",
        transmission: "Automatic",
        discount: 0,
        ratings: 5,
    },
]


export const carDatabase = [
    {
        id: "609e451f60c175001eab94ff",
        matriculeNumber: "MERCEDES-G-CLASS-001",
        make: "Mercedes-Benz",
        model: "G-Class",
        year: 2023,
        color: "Black",
        mileage: 5000,
        price: 150,
        description: "Luxury SUV with superior off-road capability.",
        imageUrl: "../images/Cars/Mercedes-Benz-G-Class.png",
        isAvailable: true,
        isTop: false,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609e451f60c175001eab92ff",
        matriculeNumber: "MERCEDES-GLA-001",
        make: "Mercedes-Benz",
        model: "GLA",
        year: 2022,
        color: "Silver",
        mileage: 10000,
        price: 120,
        description: "Compact luxury SUV with sporty handling.",
        imageUrl: "../images/Cars/Mercedes-Benz-GLA.png",
        isAvailable: true,
        isTop: false,
        isRecommended: false,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609e451f60c175001eab91ff",
        matriculeNumber: "MERCEDES-GLC-COUPE-001",
        make: "Mercedes-Benz",
        model: "GLC Coupe",
        year: 2023,
        color: "White",
        mileage: 8000,
        price: 140,
        description: "Elegant coupe-style SUV with powerful performance.",
        imageUrl: "../images/Cars/Mercedes-Benz-GLC-Coupe.png",
        isAvailable: true,
        isTop: false,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609e451f60c175001eab90ff",
        matriculeNumber: "MERCEDES-GLS-001",
        make: "Mercedes-Benz",
        model: "GLS",
        year: 2023,
        color: "Blue",
        mileage: 6000,
        price: 180,
        description: "Full-size luxury SUV with exceptional comfort.",
        imageUrl: "../images/Cars/Mercedes-Benz-GLS.png",
        isAvailable: true,
        isTop: true,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609e451f60c175001eab85ff",
        matriculeNumber: "MERCEDES-S-CLASS-001",
        make: "Mercedes-Benz",
        model: "S-Class",
        year: 2023,
        color: "Black",
        mileage: 2000,
        price: 250,
        description: "Ultimate luxury sedan with advanced technology.",
        imageUrl: "../images/Cars/Mercedes-Benz-S-Class.png",
        isAvailable: true,
        isTop: true,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609e451f60c175001eab15ff",
        matriculeNumber: "PORSCHE-CAYENNE-001",
        make: "Porsche",
        model: "Cayenne",
        year: 2023,
        color: "Red",
        mileage: 7000,
        price: 200,
        description: "High-performance luxury SUV.",
        imageUrl: "../images/Cars/Porsche-Cayenne.png",
        isAvailable: true,
        isTop: false,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609d451f60c175001eab95ff",
        matriculeNumber: "PORSCHE-MACAN-TURBO-EV-001",
        make: "Porsche",
        model: "Macan Turbo EV",
        year: 2023,
        color: "Blue",
        mileage: 3000,
        price: 220,
        description: "Electric SUV with sporty performance.",
        imageUrl: "../images/Cars/Porsche-Macan-Turbo-EV.png",
        isAvailable: true,
        isTop: false,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "612e451f60c175001eab95ff",
        matriculeNumber: "PORSCHE-TAYCAN-001",
        make: "Porsche",
        model: "Taycan",
        year: 2023,
        color: "White",
        mileage: 4000,
        price: 280,
        description: "High-performance electric sedan.",
        imageUrl: "../images/Cars/Porsche-Taycan.png",
        isAvailable: true,
        isTop: true,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "149e451f60c175001eab95ff",
        matriculeNumber: "PORSCHE-911-001",
        make: "Porsche",
        model: "911",
        year: 2023,
        color: "Yellow",
        mileage: 2000,
        price: 300,
        description: "Iconic sports car with exceptional performance.",
        imageUrl: "../images/Cars/Porsche-911.png",
        isAvailable: true,
        isTop: true,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "6044451f60c175001eab95ff",
        matriculeNumber: "ASTON-MARTIN-DB11-001",
        make: "Aston Martin",
        model: "DB11",
        year: 2023,
        color: "Green",
        mileage: 1500,
        price: 350,
        description: "Luxury sports car with elegant design.",
        imageUrl: "../images/Cars/Aston Martin DB11.jpg",
        isAvailable: true,
        isTop: true,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609d551f60c175001eab95ff",
        matriculeNumber: "AUDI-Q3-001",
        make: "Audi",
        model: "Q3",
        year: 2022,
        color: "Gray",
        mileage: 12000,
        price: 100,
        description: "Compact luxury SUV with advanced features.",
        imageUrl: "../images/Cars/Audi Q3.jpg",
        isAvailable: true,
        isTop: false,
        isRecommended: false,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609e781f60c175001eab95ff",
        matriculeNumber: "AUDI-Q7-001",
        make: "Audi",
        model: "Q7",
        year: 2023,
        color: "Black",
        mileage: 8000,
        price: 160,
        description: "Full-size luxury SUV with advanced technology.",
        imageUrl: "../images/Cars/Audi Q7.jpg",
        isAvailable: true,
        isTop: false,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609e451f60c144001eab95ff",
        matriculeNumber: "JEEP-GRAND-CHEROKEE-001",
        make: "Jeep",
        model: "Grand Cherokee",
        year: 2023,
        color: "White",
        mileage: 10000,
        price: 130,
        description: "Midsize SUV with excellent off-road capabilities.",
        imageUrl: "../images/Cars/jeep grand cherokee.jpg",
        isAvailable: true,
        isTop: false,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609e451f111175001eab95ff",
        matriculeNumber: "JEEP-WRANGLER-001",
        make: "Jeep",
        model: "Wrangler",
        year: 2023,
        color: "Blue",
        mileage: 9000,
        price: 140,
        description: "Iconic off-road SUV with rugged capabilities.",
        imageUrl: "../images/Cars/jeep wrangler.jpg",
        isAvailable: true,
        isTop: false,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609e451f70c175001eab95ff",
        matriculeNumber: "LAND-ROVER-DEFENDER-001",
        make: "Land Rover",
        model: "Defender",
        year: 2023,
        color: "Silver",
        mileage: 6000,
        price: 200,
        description: "Rugged luxury SUV with off-road prowess.",
        imageUrl: "../images/Cars/land rover defender.jpg",
        isAvailable: true,
        isTop: true,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
    {
        id: "609e651f60c175001eab95ff",
        matriculeNumber: "LAND-ROVER-RANGE-ROVER-001",
        make: "Land Rover",
        model: "Range Rover",
        year: 2023,
        color: "Black",
        mileage: 5000,
        price: 250,
        description: "Ultimate luxury SUV with superior comfort.",
        imageUrl: "../images/Cars/Land Rover range rover.jpg",
        isAvailable: true,
        isTop: true,
        isRecommended: true,
        isNew: true,
        createdAt: new Date(),
    },
];
