import img1 from "../images/Cars/car11.png"
import img2 from "../images/Cars/car22.png"
import img3 from "../images/Cars/car1.png"

// data.jsx

const carsData = [
  {
    id: 1,
    name: "Toyota Corolla",
    category: "Sedan",
    image: img1,
    gas: "Gasoline",
    gear: "Automatic",
    capacity: "5",
    price: 50.0,
    discount: 10.0,
    isTop: false,
    isRecommended: false,
    isRented: false,
    isNew: true,
    isVip: false,
    isBusinessClass: false,
    isAssurance: true,
  },
  {
    id: 2,
    name: "Honda Civic",
    category: "Sedan",
    image: img2,
    gas: "Gasoline",
    gear: "Automatic",
    capacity: "5",
    price: 55.0,
    discount: null,
    isTop: false,
    isRecommended: true,
    isRented: false,
    isNew: false,
    isVip: false,
    isBusinessClass: true,
    isAssurance: false,
  },
  {
    id: 3,
    name: "Ford Mustang",
    category: "Coupe",
    image: img3,
    gas: "Gasoline",
    gear: "Manual",
    capacity: "4",
    price: 100.0,
    discount: 5.0,
    isTop: false,
    isRecommended: true,
    isRented: true,
    isNew: false,
    isVip: true,
    isBusinessClass: false,
    isAssurance: true,
  },
  {
    id: 4,
    name: "Ford Mustang",
    category: "Coupe",
    image: img3,
    gas: "Gasoline",
    gear: "Manual",
    capacity: "4",
    price: 100.0,
    discount: 5.0,
    isTop: true,
    isRecommended: true,
    isRented: true,
    isNew: false,
    isVip: true,
    isBusinessClass: false,
    isAssurance: true,
  },
  {
    id: 5,
    name: "Ford Mustang",
    category: "Coupe",
    image: img3,
    gas: "Gasoline",
    gear: "Manual",
    capacity: "4",
    price: 100.0,
    discount: 5.0,
    isTop: true,
    isRecommended: true,
    isRented: true,
    isNew: false,
    isVip: true,
    isBusinessClass: false,
    isAssurance: true,
  },
  {
    id: 6,
    name: "Ford Mustang",
    category: "Toyota",
    image: img3,
    gas: "Gasoline",
    gear: "Manual",
    capacity: "4",
    price: 100.0,
    discount: 5.0,
    isTop: true,
    isRecommended: true,
    isRented: true,
    isNew: false,
    isVip: true,
    isBusinessClass: false,
    isAssurance: true,
  },
  // Add more cars as needed
];

export default carsData;
